name: Build Python-miio for ARMv7 using QEMU

on:
  push:
    branches:
      - main  # 自动触发条件：当 main 分支有新的提交时
  pull_request:
    branches:
      - main  # 自动触发条件：当有 PR 合并到 main 分支时
  workflow_dispatch:  # 手动触发条件

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU for ARM
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm

      - name: Set up Python for ARMv7
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support
          sudo update-binfmts --install arm /usr/bin/qemu-arm-static --magic '\x7fELF\x01\x01\x01\x03\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x28\x00\x01\x00\x00\x00' --mask '\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff'

      - name: Create virtual environment and install python-miio
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install git+https://github.com/rytilahti/python-miio.git
          python -c 'import miio; print(miio.__version__)' > version.txt

      - name: Archive virtual environment
        run: |
          tar -czvf python-miio-armv7.tar.gz venv/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-miio-armv7
          path: |
            python-miio-armv7.tar.gz
            version.txt
