

name: ARMv7 Build python-miio

on: [push]

jobs:
  build:
    name: Build for ARMv7
    runs-on: ubuntu-latest
    steps:
      - name: Run in ARMv7 container
        run: |
          docker run --rm --platform arm32v7/python:3 \
            /bin/bash -c "
            python -m venv python-miio-git &&
            source python-miio-git/bin/activate &&
            pip install git+https://github.com/rytilahti/python-miio.git &&
            git clone https://github.com/luochen88/python-miio-git.git shell &&
            cp shell/{miplug.sh override,yaml} python-miio/ &&
            tar -zcvf python-miio-git.tar.gz python-miio
            pytest tests/ &&

            "
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8


