name: Build Python-miio for ARMv7

on:
  push:
    branches:
      - main  # 你可以根据需要更改分支名称

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # 你可以根据需要更改 Python 版本

      - name: Install QEMU for ARMv7
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install python-miio

      - name: Test Python-miio installation
        run: |
          python -c "import miio; print(miio.__version__)"

      - name: Archive virtual environment
        run: |
          tar -czvf python-miio-armv7.tar.gz venv/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: python-miio-armv7
          path: python-miio-armv7.tar.gz
