name: Build Python-miio for ARMv7

on:
  push:
    branches:
      - main  # 触发分支，可以根据需要修改
  pull_request:
    branches:
      - main  # 如果有 PR 到 main 分支时也触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub (optional)
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and run in ARMv7 container
        run: |
          docker run --rm --platform linux/arm/v7 -v $(pwd):/workspace -w /workspace arm32v7/python:3-slim \
          /bin/sh -c "
          python -m venv venv && \
          . venv/bin/activate && \
          pip install --upgrade pip && \
          pip install python-miio && \
          python -c 'import miio; print(miio.__version__)'
          "

      - name: Archive virtual environment
        run: |
          tar -czvf python-miio-armv7.tar.gz venv/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: python-miio-armv7
          path: python-miio-armv7.tar.gz
