

name: ARMv7 Build python-miio

on: [push]

jobs:
  build:
    name: Build for ARMv7
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ARMv7 environment
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm/v7
          tags: python-armv7-env
          load: true

      - name: Run in ARMv7 container
        run: |
          docker run --rm --platform linux/arm/v7 python-armv7-env \
            /bin/bash -c "
            python -m venv python-miio-git &&
            source python-miio-git/bin/activate &&
            pip install git+https://github.com/rytilahti/python-miio.git &&
            git clone https://github.com/luochen88/python-miio-git.git shell &&
            cp shell/{miplug.sh override,yaml} python-miio/ &&
            tar -zcvf python-miio-git.tar.gz python-miio
            pytest tests/ &&

            "
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8


